name: lite_embeddings_dart
description: An LLM Embeddings tool for Dart
version: 0.3.0
repository: https://github.com/LiteVar/lite_embeddings_dart

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  uuid: ^4.4.0
  dart_openai: ^5.1.0
  chromadb: ^0.2.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
